### PR TITLE
Add missing bionic kernels including 4.18 kernels

### PR DESCRIPTION
**Pull request by brycekahle**

### CODE REVIEW

**Comment by rafaeldtinoco** [comment]
Hum, there is catch here.. I see you are re-adding a bunch of kernels (5.4 for example) that already have BTF support (they were compiled with recent pahole when that userland tool got updated per my request).

I know by heart that 5.4.0-92 already has BTF info, for example. Unsure about the -aws- ones, will have to check.

With that said, I'll have to go through generated BTF files and remove those that already have BTF enabled, just fyio (no worries on your side).

**Comment by brycekahle** [comment]
There is a nice way to check in the script for existing BTF. I can add it for Ubuntu and re-run the script.

**Comment by rafaeldtinoco** [comment]
> There is a nice way to check in the script for existing BTF. I can add it for Ubuntu and re-run the script.

Yep, I was just running bpftool and checking for types that only exist when BTF info is embedded, then discarding those kernels (as we don't need them).

**Comment by brycekahle** [comment]
I've been checking for the `.BTF` ELF section in the `vmlinux` file itself.

**Comment by brycekahle** [comment]
Script is still running, but so far it appears the `generic`,`aws`, and `gcp` kernels have BTF after a certain version, but the `azure` and `gke` don't yet.

**Comment by brycekahle** [comment]
OK. Updated. For reference, I believe these are the first versions with BTF embedded in the kernel:

### x86_64

| Flavor | Version |
| ------ | ------- |
| azure | `linux-image-unsigned-5.4.0-1065-azure-dbgsym` |
| gcp | `linux-image-unsigned-5.4.0-1059-gcp-dbgsym` |
|gke | `linux-image-unsigned-5.4.0-1071-gke-dbgsym` |
| aws | `linux-image-unsigned-5.4.0-1061-aws-dbgsym` |
| generic | `linux-image-unsigned-5.4.0-92-generic-dbgsym` |

### arm64

| Flavor | Version |
| ------ | ------- |
| azure | `linux-image-unsigned-5.4.0-1078-azure-dbgsym` |
| gcp | `linux-image-unsigned-5.4.0-1072-gcp-dbgsym` |
|gke | `linux-image-unsigned-5.4.0-1071-gke-dbgsym` |
| aws | `linux-image-unsigned-5.4.0-1061-aws-dbgsym` |
| generic | `linux-image-unsigned-5.4.0-92-generic-dbgsym` |

**Pull request merged**
